services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - event
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/gateway

  auth:
    build: ./auth
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=supersecret

  event:
    build: ./event
    ports:
      - "3002:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/event

volumes:
  mongo_data:
